features_path: ./data/tmp_features
output_path: ./exp
num_epochs: 200
batch_size: 8
max_protein_length: 2000
device: cuda
n_cycles: 0
linear_layers_num: 3
alternative_noising: true
dropout: 0.1
noise_std: 5
diffusion: false
message_passing: gvpe
initial_patch_size: 256